### ISSUE TITLE
How do I correctly create a deferred credit journal entry?

### ISSUE THREAD

**Issue by jmichaelterenin** [scottlaurent/accounting#1]
Hi Scott,

First off, and most importantly, thank you for building and sharing this package with the public.

I've developed a Laravel booking reservation website that the owner would like to be able to integrate with QBO or Xero. I believe it would be helpful to have an accounting database design included to help facilitate the syncing of booking transactions and monthly invoices. Here's the scenario that has prompted that direction:

The website will offer commission-free bookings for the first 3 months to the owners of listings. It also offers a refer-a-friend system that provides a set amount or percentage off discount to the end-user (customer) that has been referred or has referred someone who completed a booking. That set amount or percentage discount is applied to the commission owed the website owner. However, since the bookings are commission-free for the first 3 months, the listing owner will not be able to take advantage of the discount off his/her commission. Therefore, the website owner would like to credit the listing owner that amount, to be redeemed when the listing owner has bookings that occur after the 3-month commission-free period. Invoices are sent out on a monthly basis for bookings completed within the month.

Here's an example (basically said another way):

Listing Owner A signs up to the website and agrees to pay the website owner a 10% commission rate for bookings through the website. Listing Owner A gets a 3-month commission-free period.
Refer-A-Friend offers a $50 discount to the customer with a booking over $500. 

Listing Owner A receives a booking for $600 through the Refer-A-Friend promotion during the commission-free period. He pays no commission on the booking, but is credited with $50. The customer only pays $550 for the booking.

Listing Owner A receives a straight booking for $1000 during the period when commission is now at 10%. He owes the website owner $100, but because he has a $50 commission credit, he only has to pay $50. The customer is still paying $1000 for the booking.

Can you explain how this is achieved through an accounting journal-entry system? I debated whether I should post this on stackoverflow.com, or here, but decided on here since I am wanting to utilize your package, and want to make sure it is able to handle this scenario. I hope it is not asking too much, but I must admit: I've never taken an accounting class in college, and haven't found much luck in finding a solution through googling. 

Thanks in advance!

**Comment by scottlaurent** [comment]
so the thing it sounds like you are doing here is accruing mini-accounts for the LO's (listing owners).  one thing I'm not clear on is whether the 10% is applied before or after the discount is applied.  I will assume it is applied after (but just adjust what I'm saying if you do it differently).

walking through the transactions above:

1. "Listing Owner A (LOA) receives a booking for $600 through the Refer-A-Friend promotion during the commission-free period."
  - increase $50 liability account ("LOA balance") -- this is what the website owes LOA.  So when LOA logs in, it will look like money they are owed. 
  - decrease revenue $50

-- this may seem counter intuitive, however what you are doing here really comes down to the fact that the website owner is "paying" money out to LOA -- and while cash doesn't change hands, in theory, at the time of the transaction, the money is technically owed to LOA.

2. "Listing Owner A receives a straight booking for $1000 during the period when commission is now at 10%."
  - decrease $100 liability account ("LOA balance") -- this is what the website owes LOA.  So when LOA logs in, they will now see a -$50 which means they owe $50 
  - increase revenue $100 - so now it looks like website earned $50 total (because remember they have the decrease in step 1

So after 1 and 2, you will have $50 owned to website and $50 income to the web site.

When LOA actually does pay the $50... just increase the cash account, increase the liability account to LOA (which functions as a credit in this case) -- and don't touch the revenue account because this is just a cash payment and the income was already recorded.

So, your original question of a "deferred credit entry" doesn't exactly apply.  You are not deferring the entry.  You are tracking it when it occurs and altering how it's looked at, since from a company (website) perspective, it's an expense.

You should also make *VERY* clear to LOA that a credit balance doesn't mean that they can redeem that for cash.  In other words, the credit was just added to their account contingent upon being used against future income.  This is a common practice, but still it's accounted for as I'm explaining above.

**Comment by scottlaurent** [comment]
here is a code sample.  you would need 2 (or 3) journals.  One for the user (the LOA), the second is a sales journal for the company.  Normally what I do is create a table in the db called system_journals and each record represents a different journal.  Almost always the very 1st one is for sales.  Then depending on the client, we create a cash one (etc) depending on how complex they want to make it.  


transaction 1

```
$loa->journal->creditDollars(50); // they now have a credit of $50
\App\Model\SystemJournals::where('type','sales')->first()->journal->debitDollars(50); // company income is now $-50
```

transaction 2
```
$loa->journal->debitDollars(100); // they now have a deficit of $50 (they owe)
\App\Model\SystemJournals::where('type','sales')->first()->journal->creditDollars(100); // company income is now $50
```

upon payment of the $50
```
$loa->journal->creditDollars(50); // they now have a $0 balance

// this line isn't necessary unless you really just want to enforce your double entry stuff...
\App\Model\SystemJournals::where('type','cash')->first()->journal->creditDollars(50); // company cash balance is now $50
```

And as a final note, you could actually just bypass all of the \App\Model\SystemJournals stuff and do only the $loa->journal as I'm showing above, but by doing that, it's not as easy to really determine the income quickly because as payments are made and the $loa balances are changed, you lose track of company income overall and would have to resort to SUMMING the entire jounral tables for credits/debits.  A better way to at minimum maintain at least one \App\Model\SystemJournals model and give it a journal that you trigger every time you trigger an LOA journal (double entry...)

**Comment by jmichaelterenin** [comment]
Hi Scott,
Thanks for replying on the holiday, hope you enjoyed your extended weekend!

Just to answer your question: the 10% commission fee to the website is applied before the discount is applied. It's just the way it was explained to me as a requirement by the website owner.

The concept of journals, and having 2 (or more) is what I think I was missing when figuring out how to handle this scenario. And as you've mentioned, it's a more complicated accounting system to only maintain an LO journal. I assume I'll have an LO journal for every listing, as it is possible for an owner to have multiple listings. 

Sounds like I can use your package and benefit from it when integrating with QBO or Xero, and I appreciate your reply/feedback greatly. I'm in the middle of an upgrade for Laravel from 4.2 to 5.4, so I'll resume this in the near future.

Thanks again!

**Comment by scottlaurent** [comment]
you dont need multiple journals.  just one.  the transaction object (the sale object or whatever) would be connected to the propert and then just saved as the coonected object to the journal entry.  so like: $order->save(), then user->journal->attachTo($order).  in this way could easily determine which orders were connected to which properties.  but you will probably only want ro keep a single journal per user. 



On 29 de mayo de 2017, 9:16:11 PM MST, jmichaelterenin <notifications@github.com> wrote:Hi Scott, Thanks for replying on the holiday, hope you enjoyed your extended weekend!  Just to answer your question: the 10% commission fee to the website is applied before the discount is applied. It's just the way it was explained to me as a requirement by the website owner.  The concept of journals, and having 2 (or more) is what I think I was missing when figuring out how to handle this scenario. And as you've mentioned, it's a more complicated accounting system to only maintain an LO journal. I assume I'll have an LO journal for every listing, as it is possible for an owner to have multiple listings.  Sounds like I can use your package and benefit from it when integrating with QBO or Xero, and I appreciate your reply/feedback greatly. I'm in the middle of an upgrade for Laravel from 4.2 to 5.4, so I'll resume this in the near future.  Thanks again!  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/scottlaurent/accounting","title":"scottlaurent/accounting","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/scottlaurent/accounting"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jmichaelterenin in #1: Hi Scott,\r\nThanks for replying on the holiday, hope you enjoyed your extended weekend!\r\n\r\nJust to answer your question: the 10% commission fee to the website is applied before the discount is applied. It's just the way it was explained to me as a requirement by the website owner.\r\n\r\nThe concept of journals, and having 2 (or more) is what I think I was missing when figuring out how to handle this scenario. And as you've mentioned, it's a more complicated accounting system to only maintain an LO journal. I assume I'll have an LO journal for every listing, as it is possible for an owner to have multiple listings. \r\n\r\nSounds like I can use your package and benefit from it when integrating with QBO or Xero, and I appreciate your reply/feedback greatly. I'm in the middle of an upgrade for Laravel from 4.2 to 5.4, so I'll resume this in the near future.\r\n\r\nThanks again!"}],"action":{"name":"View Issue","url":"https://github.com/scottlaurent/accounting/issues/1#issuecomment-304770754"}}}
